# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


md = dplyr::starwars


# Without random effects

mod = brms_model(Chainset = "long", 
           Response = "mass", 
           FixedEffect = c("sex","height"), 
           Family = "gaussian", 
           Data = md, 
          Seed = 0405)

print(mod)

plot(mod)

# With random effect
mod_RE = brms_model(Chainset = "long", 
           Response = "mass", 
           FixedEffect = c("sex","height"), 
           RandomEffect = "species", 
           Family = "gaussian", 
           Data = md, 
           Seed = 0405)

print(mod_RE)

plot(mod_RE)


# With random slope
mod_RS = brms_model(Chainset = "long", 
           Response = "mass", 
           FixedEffect = c("sex","height"), 
           RandomEffect = "species", 
           RandomSlope = "height",
           Family = "gaussian", 
           Data = md, 
          Seed = 0405)

print(mod_RS)

plot(mod_RS)



