# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

data("mod_re", package = "VarDecomp")
data("mod_rs", package = "VarDecomp")

compare_slopes(mod_re, mod_rs, Slope = "height")
