# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


test_plot_R2 = function(brmsfit){
a = plot_R2(brmsfit)
b = plot_R2(brmsfit, Label = "box")
c = plot_R2(brmsfit, PlotType = "bar", Label = "text")
d = plot_R2(brmsfit, PlotType = "bar", Label = "box")
e = plot_R2(brmsfit, PlotType = "bar", Break = TRUE)

return(list(a,b,c,e,d))

}

#brms_model

# Gaussian models

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod.RData")
test_plot_R2(gau_mod)


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_re.RData")
test_plot_R2(gau_mod_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_2re.RData")
test_plot_R2(gau_mod_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_rs.RData")
test_plot_R2(gau_mod_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_rsre.RData")
test_plot_R2(gau_mod_rsre)

# Poisson models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod.RData")
test_plot_R2(poi_mod)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_re.RData")
test_plot_R2(poi_mod_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_2re.RData")
test_plot_R2(poi_mod_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_rs.RData")
test_plot_R2(poi_mod_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_rsre.RData")
test_plot_R2(poi_mod_rsre)

# Binomial models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod.RData")
test_plot_R2(bin_mod)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_re.RData")
test_plot_R2(bin_mod_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_2re.RData")
test_plot_R2(bin_mod_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_rs.RData")
test_plot_R2(bin_mod_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_rsre.RData")
test_plot_R2(bin_mod_rsre)

#brms_cov_model

# Gaussian models

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov.RData")
test_plot_R2(gau_mod_cov)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_re.RData")
test_plot_R2(gau_mod_cov_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_2re.RData")
test_plot_R2(gau_mod_cov_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_rs.RData")
test_plot_R2(gau_mod_cov_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_rsre.RData")
test_plot_R2(gau_mod_cov_rsre)

# Poisson models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov.RData")
test_plot_R2(poi_mod_cov)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_re.RData")
test_plot_R2(poi_mod_cov_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_2re.RData")
test_plot_R2(poi_mod_cov_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_rs.RData")
test_plot_R2(poi_mod_cov_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_rsre.RData")
test_plot_R2(poi_mod_cov_rsre)


# Binomial models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov.RData")
test_plot_R2(bin_mod_cov)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_re.RData")
test_plot_R2(bin_mod_cov_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_2re.RData")
test_plot_R2(bin_mod_cov_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_rs.RData")
test_plot_R2(bin_mod_cov_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_rsre.RData")
test_plot_R2(bin_mod_cov_rsre)

