# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

md = dplyr::starwars

# Centering variables
md = md %>% 
  dplyr::select(mass, sex, height, species) %>% 
  dplyr::mutate(mass = log(mass),
         sex = dplyr::recode(sex, "male" = 1, 
                      "female" = -1, 
                      "hermaphroditic" = 0,
                      "none" = as.numeric(NA)))


# Without random effects

mod = brms_model(Chainset= 2,
                 Response = "mass", 
                 FixedEffect = c("sex","height"), 
                 Family = "gaussian", 
                 Data = md)

model_fit(mod)

# With random effect
mod_RE = brms_model(Chainset= 2,
                     Response = "mass", 
                     FixedEffect = c("sex","height"), 
                     RandomEffect = "species", 
                     Family = "gaussian", 
                     Data = md)

model_fit(mod_RE)

# With random slope
mod_RS = brms_model(Chainset= 2,
                     Response = "mass", 
                     FixedEffect = c("sex","height"), 
                     RandomEffect = "species", 
                     RandomSlope = "height",
                     Family = "gaussian", 
                     Data = md)

model_fit(mod_RS)

