# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

<<<<<<< HEAD
#var_decomp(mod)
#var_decomp(mod_RE)
#var_decomp(mod_RS)
=======
var_decomp(mod)
var_decomp(mod_RE)
var_decomp(mod_RS)
>>>>>>> af97628ebcc06aa45f5ce11252a028ccf73861bd
