# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

# Define parameters for the simulation
n = 1000  # number of observations

# Simulate the data directly into a tibble
md = tibble::tibble(
  group1 = factor(sample(1:5, n, replace = TRUE)),
  group2 = factor(sample(1:10, n, replace = TRUE)),
  group3 = factor(sample(1:7, n, replace = TRUE)),
  f_var = factor(sample(1:3, n, replace = TRUE)),
  n_var1 = rnorm(n, mean = 0, sd = 1),
  n_var2 = rnorm(n, mean = 5, sd = 2),
  resp_gaussian = rnorm(n, mean = 10, sd = 3),
  resp_poisson = rpois(n, lambda = 2),
  successes = rbinom(n, size = 20, prob = 0.3)
) %>% 
  dplyr::mutate(trials = sample(1:4, n, replace = TRUE)*successes)



## Create a covariance matrix (e.g., relatedness matrix)
cov_matrix = matrix(rnorm(10 * 10), 10, 10)
cov_matrix = cov_matrix %*% t(cov_matrix)  # Make it positive semi-definite
rownames(cov_matrix) = colnames(cov_matrix) = 1:10

## Ensure the covariance matrix is symmetric
cov_matrix = (cov_matrix + t(cov_matrix)) / 2




# Gaussian model

gau_mod_cov = brms_cov_model(Chainset = 0, 
           Response = "resp_gaussian", 
           FixedEffect = c("f_var","n_var1"),
           ID = "group2", 
           Matrix = cov_matrix,
           Family = "gaussian", 
           Data = md)

# save(gau_mod_cov, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov.RData", compress = "xz")


# Gaussian models

## Fixed effects only

gau_mod_cov = brms_cov_model(Chainset = 0,
                 Response = "resp_gaussian", 
                 ID = "group2", 
                 Matrix = cov_matrix,
                 FixedEffect = c("f_var","n_var1"), 
                 Family = "gaussian", 
                 Data = md)

# save(gau_mod_cov, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov.RData", compress = "xz")


## With random effect
gau_mod_cov_re = brms_cov_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = "group1", 
                     Family = "gaussian", 
                     Data = md)


# save(gau_mod_cov_re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_re.RData", compress = "xz")

## With two random effects
gau_mod_cov_2re = brms_cov_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = c("group1","group3"), 
                     Family = "gaussian", 
                     Data = md)


# save(gau_mod_cov_2re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_2re.RData", compress = "xz")


## With random slope
gau_mod_cov_rs = brms_cov_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     Family = "gaussian", 
                     Data = md)

# save(gau_mod_cov_rs, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_rs.RData",compress = "xz")


## With random slope and an additional random effect
gau_mod_cov_rsre = brms_cov_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     RandomEffect = "group3",
                     Family = "gaussian", 
                     Data = md)

# save(gau_mod_cov_rsre, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_rsre.RData",compress = "xz")





# Poisson models

## Fixed effects only

poi_mod_cov = brms_cov_model(Chainset = 1,
                 Response = "resp_poisson", 
                 ID = "group2", 
                 Matrix = cov_matrix,
                 FixedEffect = c("f_var","n_var1"), 
                 Family = "poisson", 
                 Data = md)

# save(poi_mod_cov, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov.RData", compress = "xz")


## With random effect
poi_mod_cov_re = brms_cov_model(Chainset = 1,
                     Response = "resp_poisson", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = "group1", 
                     Family = "poisson", 
                     Data = md)


# save(poi_mod_cov_re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_re.RData", compress = "xz")

## With two random effects
poi_mod_cov_2re = brms_cov_model(Chainset = 1,
                     Response = "resp_poisson", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = c("group1","group3"), 
                     Family = "poisson", 
                     Data = md)


# save(poi_mod_cov_2re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_2re.RData", compress = "xz")


## With random slope
poi_mod_cov_rs = brms_cov_model(Chainset = 1,
                     Response = "resp_poisson", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     Family = "poisson", 
                     Data = md)

# save(poi_mod_cov_rs, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_rs.RData",compress = "xz")


## With random slope and an additional random effect
poi_mod_cov_rsre = brms_cov_model(Chainset = 1,
                     Response = "resp_poisson", 
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     RandomEffect = "group3",
                     Family = "poisson", 
                     Data = md)

# save(poi_mod_cov_rsre, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_rsre.RData",compress = "xz")






# Binomial models

## Fixed effects only

bin_mod_cov = brms_cov_model(Chainset = 0,
                 Response = "successes",
                 Trials = "trials",
                 ID = "group2", 
                 Matrix = cov_matrix,
                 FixedEffect = c("f_var","n_var1"), 
                 Family = "binomial", 
                 Data = md)

# save(bin_mod_cov, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov.RData", compress = "xz")


## With random effect
bin_mod_cov_re = brms_cov_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = "group1", 
                     Family = "binomial", 
                     Data = md)


# save(bin_mod_cov_re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_re.RData", compress = "xz")

## With two random effects
bin_mod_cov_2re = brms_cov_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = c("group1","group3"), 
                     Family = "binomial", 
                     Data = md)


# save(bin_mod_cov_2re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_2re.RData", compress = "xz")


## With random slope
bin_mod_cov_rs = brms_cov_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     Family = "binomial", 
                     Data = md)

# save(bin_mod_cov_rs, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_rs.RData",compress = "xz")


## With random slope and an additional random effect
bin_mod_cov_rsre = brms_cov_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     ID = "group2", 
                     Matrix = cov_matrix,
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     RandomEffect = "group3",
                     Family = "binomial", 
                     Data = md)

# save(bin_mod_cov_rsre, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_rsre.RData",compress = "xz")


