# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

<<<<<<< HEAD
#var_decomp(mod)
#var_decomp(mod_RE)
#var_decomp(mod_RS)
=======
<<<<<<< HEAD
#var_decomp(mod)
#var_decomp(mod_RE)
#var_decomp(mod_RS)
=======
var_decomp(mod)
var_decomp(mod_RE)
var_decomp(mod_RS)
>>>>>>> af97628ebcc06aa45f5ce11252a028ccf73861bd
>>>>>>> c07815e86fcaf55676493e1c7de825acf3d3b5b1
