# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


md = dplyr::starwars

# Centering variables
md = md %>% 
  dplyr::select(mass, sex, height, species) %>% 
  dplyr::mutate(mass = log(mass),
         sex = dplyr::recode(sex, "male" = 1, 
                      "female" = -1, 
                      "hermaphroditic" = 0,
                      "none" = as.numeric(NA)))


# Without random effects

mod = brms_model(Chainset = 2,
                 Response = "mass", 
                 FixedEffect = c("sex","height"), 
                 Family = "gaussian", 
                 Data = md)

print(mod)

plot(mod)

# With random effect
mod_RE = brms_model(Chainset = 2,
                     Response = "mass", 
                     FixedEffect = c("sex","height"), 
                     RandomEffect = "species", 
                     Family = "gaussian", 
                     Data = md)

print(mod_RE)

plot(mod_RE)


# With random slope
mod_RS = brms_model(Chainset = 2,
                     Response = "mass", 
                     FixedEffect = c("sex","height"), 
                     RandomEffect = "species", 
                     RandomSlope = "height",
                     Family = "gaussian", 
                     Data = md)

print(mod_RS)

plot(mod_RS)



#save(mod, file="mod.RData")
#save(mod_RE, file="mod_RE.RData")
#save(mod_RS, file="mod_RS.RData")
