# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


model_summary(VarDecomp::mod)

model_summary(VarDecomp::mod_RE)

model_summary(VarDecomp::mod_RS)

model_summary(VarDecomp::mod_cov)

