# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

data("mod", package = "VarDecomp")
var_decomp(mod)

data("mod_RE", package = "VarDecomp")
var_decomp(mod_RE)

data("mod_RS", package = "VarDecomp")
var_decomp(mod_RS)


data("mod_cov", package = "VarDecomp")
var_decomp(mod_cov)

