# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


data("mod", package = "VarDecomp")
model_summary(mod)

data("mod_RE", package = "VarDecomp")
model_summary(mod_RE)

data("mod_RS", package = "VarDecomp")
model_summary(mod_RS)


data("mod_cov", package = "VarDecomp")
model_summary(mod_cov)

