# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


var_decomp(VarDecomp::mod)

var_decomp(VarDecomp::mod_RE)

var_decomp(VarDecomp::mod_RS)

var_decomp(VarDecomp::mod_cov)

