# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#brms_model

# Gaussian models

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod.RData")
plot_intervals(gau_mod)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_re.RData")
plot_intervals(gau_mod_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_2re.RData")
plot_intervals(gau_mod_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_rs.RData")
plot_intervals(gau_mod_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_rsre.RData")
plot_intervals(gau_mod_rsre)

# Poisson models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod.RData")
plot_intervals(poi_mod)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_re.RData")
plot_intervals(poi_mod_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_2re.RData")
plot_intervals(poi_mod_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_rs.RData")
plot_intervals(poi_mod_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_rsre.RData")
plot_intervals(poi_mod_rsre)


# Binomial models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod.RData")
plot_intervals(bin_mod)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_re.RData")
plot_intervals(bin_mod_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_2re.RData")
plot_intervals(bin_mod_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_rs.RData")
plot_intervals(bin_mod_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_rsre.RData")
plot_intervals(bin_mod_rsre)


#brms_cov_model

# Gaussian models

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov.RData")
plot_intervals(gau_mod_cov)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_re.RData")
plot_intervals(gau_mod_cov_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_2re.RData")
plot_intervals(gau_mod_cov_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_rs.RData")
plot_intervals(gau_mod_cov_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_cov_rsre.RData")
plot_intervals(gau_mod_cov_rsre)

# Poisson models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov.RData")
plot_intervals(poi_mod_cov)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_re.RData")
plot_intervals(poi_mod_cov_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_2re.RData")
plot_intervals(poi_mod_cov_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_rs.RData")
plot_intervals(poi_mod_cov_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_cov_rsre.RData")
plot_intervals(poi_mod_cov_rsre)


# Binomial models


load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov.RData")
plot_intervals(bin_mod_cov)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_re.RData")
plot_intervals(bin_mod_cov_re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_2re.RData")
plot_intervals(bin_mod_cov_2re)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_rs.RData")
plot_intervals(bin_mod_cov_rs)

load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_cov_rsre.RData")
plot_intervals(bin_mod_cov_rsre)


