# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


# Gaussian models
load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_re.RData")
load(file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_rs.RData")

compare_slopes(gau_mod_re, gau_mod_rs, Slope = "n_var1")
