# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

data("mod", package = "VarDecomp")
PS_mod = var_decomp(mod)
plot_R2(PS_mod)

data("mod_RE", package = "VarDecomp")
PS_mod_RE = var_decomp(mod_RE)
plot_R2(PS_mod_RE)

data("mod_RS", package = "VarDecomp")
PS_mod_RS = var_decomp(mod_RS)
plot_R2(PS_mod_RS)

data("mod_cov", package = "VarDecomp")
PS_mod_cov = var_decomp(mod_cov)
plot_R2(PS_mod_cov)


