# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


data("mod", package = "VarDecomp")
model_fit(mod)

data("mod_re", package = "VarDecomp")
model_fit(mod_re)

data("mod_rs", package = "VarDecomp")
model_fit(mod_rs)

data("mod_cov", package = "VarDecomp")
model_fit(mod_cov)

