# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

data("mod_RE", package = "VarDecomp")
data("mod_RS", package = "VarDecomp")

compare_slopes(mod_RE, mod_RS, Slope = "height")
