# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand



# Define parameters for the simulation
n = 1000  # number of observations

# Simulate the data directly into a tibble
md = tibble::tibble(
  group1 = factor(sample(1:5, n, replace = TRUE)),
  group2 = factor(sample(1:10, n, replace = TRUE)),
  f_var = factor(sample(1:3, n, replace = TRUE)),
  n_var1 = rnorm(n, mean = 0, sd = 1),
  n_var2 = rnorm(n, mean = 5, sd = 2),
  resp_gaussian = rnorm(n, mean = 10, sd = 3),
  resp_poisson = rpois(n, lambda = 2),
  successes = rbinom(n, size = 20, prob = 0.3)
) %>% 
  dplyr::mutate(trials = sample(1:4, n, replace = TRUE)*successes)

# Gaussian models

## Fixed effects only

gau_mod = brms_model(Chainset = 0,
                 Response = "resp_gaussian", 
                 FixedEffect = c("f_var","n_var1"), 
                 Family = "gaussian", 
                 Data = md)

#save(gau_mod, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod.RData", compress = "xz")


## With random effect
gau_mod_re = brms_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = "group1", 
                     Family = "gaussian", 
                     Data = md)


#save(gau_mod_re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_re.RData", compress = "xz")

## With two random effects
gau_mod_2re = brms_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = c("group1","group2"), 
                     Family = "gaussian", 
                     Data = md)


#save(gau_mod_2re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_2re.RData", compress = "xz")


## With random slope
gau_mod_rs = brms_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     Family = "gaussian", 
                     Data = md)

#save(gau_mod_rs, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_rs.RData",compress = "xz")


## With random slope and an additional random effect
gau_mod_rsre = brms_model(Chainset = 0,
                     Response = "resp_gaussian", 
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     RandomEffect = "group2",
                     Family = "gaussian", 
                     Data = md)

# save(gau_mod_rsre, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/gau_mod_rsre.RData",compress = "xz")





# Poisson models

## Fixed effects only

poi_mod = brms_model(Chainset = 0,
                 Response = "resp_poisson", 
                 FixedEffect = c("f_var","n_var1"), 
                 Family = "poisson", 
                 Data = md)

# save(poi_mod, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod.RData", compress = "xz")


## With random effect
poi_mod_re = brms_model(Chainset = 0,
                     Response = "resp_poisson", 
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = "group1", 
                     Family = "poisson", 
                     Data = md)


# save(poi_mod_re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_re.RData", compress = "xz")

## With two random effects
poi_mod_2re = brms_model(Chainset = 0,
                     Response = "resp_poisson", 
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = c("group1","group2"), 
                     Family = "poisson", 
                     Data = md)


# save(poi_mod_2re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_2re.RData", compress = "xz")


## With random slope
poi_mod_rs = brms_model(Chainset = 0,
                     Response = "resp_poisson", 
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     Family = "poisson", 
                     Data = md)

# save(poi_mod_rs, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_rs.RData",compress = "xz")


## With random slope and an additional random effect
poi_mod_rsre = brms_model(Chainset = 0,
                     Response = "resp_poisson", 
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     RandomEffect = "group2",
                     Family = "poisson", 
                     Data = md)

# save(poi_mod_rsre, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/poi_mod_rsre.RData",compress = "xz")






# Binomial models

## Fixed effects only

bin_mod = brms_model(Chainset = 0,
                 Response = "successes",
                 Trials = "trials",
                 FixedEffect = c("f_var","n_var1"), 
                 Family = "binomial", 
                 Data = md)

# save(bin_mod, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod.RData", compress = "xz")


## With random effect
bin_mod_re = brms_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = "group1", 
                     Family = "binomial", 
                     Data = md)


# save(bin_mod_re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_re.RData", compress = "xz")

## With two random effects
bin_mod_2re = brms_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     FixedEffect = c("f_var","n_var1"), 
                     RandomEffect = c("group1","group2"), 
                     Family = "binomial", 
                     Data = md)


# save(bin_mod_2re, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_2re.RData", compress = "xz")


## With random slope
bin_mod_rs = brms_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     Family = "binomial", 
                     Data = md)

# save(bin_mod_rs, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_rs.RData",compress = "xz")


## With random slope and an additional random effect
bin_mod_rsre = brms_model(Chainset = 0,
                     Response = "successes",
                     Trials = "trials",
                     FixedEffect = c("f_var","n_var1"),
                     RandomSlope = c("n_var1", "group1"),
                     RandomEffect = "group2",
                     Family = "binomial", 
                     Data = md)

# save(bin_mod_rsre, file = "C:/Users/Gabe/Desktop/VarDecomp/dev/models/bin_mod_rsre.RData",compress = "xz")




