# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

data("mod", package = "VarDecomp")
plot_intervals(mod)

data("mod_re", package = "VarDecomp")
plot_intervals(mod_re)

data("mod_rs", package = "VarDecomp")
plot_intervals(mod_rs)


data("mod_cov", package = "VarDecomp")
plot_intervals(mod_cov)

