# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

data("mod", package = "VarDecomp")
var_decomp(mod)

data("mod_re", package = "VarDecomp")
var_decomp(mod_re)

data("mod_rs", package = "VarDecomp")
var_decomp(mod_rs)


data("mod_cov", package = "VarDecomp")
var_decomp(mod_cov)

