# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


#' Run a brms model
#'
#' @param Data A data frame containing the data - covariates should be centered to a the mean or to a meaningful zero (see Schielzeth H. 2010. Simple means to improve the interpretability of regression coefficients. Methods Ecol Evol. 1:103–113. doi:10.1111/j.2041-210X.2010.00012.x.).
#' @param Response String with the name of the column in Data containing the response variable (e.g. "mass"). 
#' @param FixedEffect String with the name of the column in Data containing the fixed effect variable (e.g. "height"). To add multiple fixed effects, use c() (e.g. c("height", "sex")). 
#' @param RandomEffect String with the name of the column in Data containing the random effect variable (e.g. "species"). The current package version allows the use of a single random effect.
#' @param RandomSlope String with the name of the column in Data containing the covariate to be added as a random slope (e.g. "height"). The current package version allows the use of a single random slope.
#' @param Chainset String to define the number of iterations. Start with "test" (warmup=10; iter=110; thin=10; chains=2) and increase as needed until convergence: "long"(warmup=15000; iter=30000; thin=15; chains=2); "longer"(warmup=30000; iter=60000; thin=30; chains=2); "longest" (warmup=60000; iter=120000; thin=60; chains=2).
#' @param Family String to define the family function in the brms model. Current supported families: "gaussian", "binomial", "poisson".
#' @param Seed Numeric and optional. Set a seed in order to repeat the results from the model when running it more than once. 
#'
#' @return Returns a brmsfit
#' @export 
#'
#' @examples
#'
#' # With random slope
#' md = dplyr::starwars
#'
#' mod = VarDecomp::brms_model(Chainset = "long", 
#'            Response = "mass", 
#'            FixedEffect = c("sex","height"), 
#'            RandomEffect = "species", 
#'            RandomSlope = "height",
#'            Family = "gaussian", 
#'            Data = md, 
#'            Seed = 0405)
#'
#' print(mod)
#'
#' plot(mod)
#'
brms_model = function(Data, Response, FixedEffect, RandomEffect = NULL, RandomSlope = NULL, Chainset, Family = "gaussian", Seed = sample(1000:9999, 1)){

  
stopifnot("`Data` must be a data frame" =               
              inherits(Data, "data.frame"))
  
stopifnot("`Response` must be a string" =               
              inherits(Response, "character"))

stopifnot("`FixedEffect` must be a string" =               
              inherits(FixedEffect, "character"))

if(!is.null(RandomEffect)) {stopifnot("`RandomEffect` must be a string" =               
              inherits(RandomEffect, "character"))}

if(!is.null(RandomSlope)){stopifnot("`RandomSlope` must be a string" =               
              inherits(RandomSlope, "character"))}

stopifnot("`Chainset` must be a string (options are 'test', 'long, 'longer', 'longest')" =               
              inherits(Chainset, "character"))

stopifnot("`Family` must be a string" =               
              inherits(Family, "character"))

stopifnot("`Seed` must be a string" =               
              inherits(Seed, "numeric"))

testfunction()
  
if(Chainset=="longest"){warmup=60000; iter=120000; thin=60; chains=2}
if(Chainset=="longer"){warmup=30000; iter=60000; thin=30; chains=2}
if(Chainset=="long"){warmup=15000; iter=30000; thin=15; chains=2}
if(Chainset=="test"){warmup=10; iter=110; thin=10; chains=2}


# Construct the formula object for models of binomial or poisson families
if(Family == "binomial" | Family == "poisson"){
Data = Data %>%
  mutate(observationID = as.factor(row_number()))

bfform = 
    
    if(is.null(RandomEffect)) {
      paste0(Response, "~", paste(FixedEffect, collapse = " + "), " + (1|observationID)")
      } else {
        if(is.null(RandomSlope)){
        paste0(Response, "~", paste(FixedEffect, collapse = " + "),
        "+ ( 1 | ", RandomEffect," ) + (1|observationID)")
          } else {
          paste0(Response, "~",
                 paste(FixedEffect, collapse = " + "),
                 "+ ( 1 +", RandomSlope, " | ", 
                 RandomEffect," ) + (1|observationID)")}}

} else {
# Construct the formula object for other model families

  bfform = 
    
    if(is.null(RandomEffect)) {
      paste0(Response, "~", paste(FixedEffect, collapse = " + "))
      } else {
        if(is.null(RandomSlope)){
        paste0(Response, "~", paste(FixedEffect, collapse = " + "),
        "+ ( 1 | ", RandomEffect," )")
          } else {
          paste0(Response, "~",
                 paste(FixedEffect, collapse = " + "),
                 "+ ( 1 +", RandomSlope, " | ", RandomEffect," )")}}
        
}

mod =  brms::brm(brms::bf(stats::as.formula(bfform)),
                  family = Family,
                  data = Data, 
                  warmup = warmup,
                  iter = iter, 
                  thin=thin, 
                  chains = chains, 
                  init = "random", 
                  seed = Seed, 
                  cores = parallel::detectCores(), 
                  control = list(adapt_delta = 0.999), 
                  sample_prior = TRUE)

brmsfit = mod

return(brmsfit)

}

