# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


#' Run a brms model
#'
#' @param Data A data frame containing the data - covariates should be centered to a the mean or to a meaningful zero (see Schielzeth H. 2010. Simple means to improve the interpretability of regression coefficients. Methods Ecol Evol. 1:103–113. doi:10.1111/j.2041-210X.2010.00012.x.).
#' @param Response String with the name of the column in Data containing the response variable (e.g. "mass").
#' @param FixedEffect String with the name of the column in Data containing the fixed effect variable (e.g. "height"). To add multiple fixed effects, use c() (e.g. c("height", "sex")). 
#' @param RandomEffect String with the name of the column in Data containing the random effect variable (e.g. "species"). The current package version allows the use of a single random effect.
#' @param RandomSlope Vector containing two values: first a string with the name of the column in Data containing the covariate to be added as a random slope, second the random effect to which the  random slope will be applied (e.g. RandomSlope = c("height", "species")). The current package version allows the use of a single random slope.
#' @param Chainset Defines the number of iterations. Start with Chainset = 1 and increase as needed until convergence. The value of Chainsetis multiplied by 15000 in warmup, 30000 in iterations and 15 in thin intervale. For quick tests use Chainset = 1 (warmup=10; iter=110; thin=10; chains=2) 
#' @param Family String to define the family function in the brms model. Current supported families: "gaussian", "binomial", "poisson".
#' @param Seed Numeric and optional. Set a seed in order to repeat the results from the model when running it more than once. 
#' @param Trials The total number of trials in a binomial model. The number of successes should be imputed on Response.
#' @param PriorSamples Logical value that defines if brmsfit will contain the priors used. Default is set to `FALSE`, which does not includ the priors in the brmsfit. 
#'
#' @return Returns a brmsfit
#' @import BH
#' @import brms
#' @import RcppEigen
#' @export 
#'
#' @examples
#' # Simulate data
#' md = tibble::tibble(
#'   group = factor(sample(1:10, 1000, replace = TRUE)),
#'   f_var = factor(sample(1:3, 1000, replace = TRUE)),
#'   n_var = rnorm(1000, mean = 0, sd = 1),
#'   resp = rnorm(1000, mean = 10, sd = 3))
#'
#' # Run model
#' mod = brms_model(Response = "resp", 
#'                  FixedEffect = c("f_var","n_var"), 
#'                  RandomEffect = "group", 
#'                  Family = "gaussian", 
#'                  Data = md)
#'
#'
#'
#'

brms_model = function(Data, Response, FixedEffect, RandomEffect = NULL, RandomSlope = NULL, 
  Chainset = 1, Family = "gaussian", Seed = NULL, Trials = NULL, PriorSamples = TRUE) {

# Testing inputs

## Data  
stopifnot("`Data` must be a data frame" = inherits(Data, "data.frame"))

## Response  
stopifnot("`Response` must be a string" = inherits(Response, "character"))


## FixedEffect
stopifnot("`FixedEffect` must be a string" = inherits(FixedEffect, "character"))

## RandomEffect
if(!is.null(RandomEffect)) {
  stopifnot("`RandomEffect` must be a string" = inherits(RandomEffect, "character"))
}

##RandomSlope
if(!is.null(RandomSlope)){
  stopifnot(
  "`RandomSlope` must be a vector containing two string values" =
  inherits(RandomSlope, "character"),
  
  "`RandomSlope` must contain two values (e.g. RandomSlope = c('covariate name', 
  'random effect')" = length(RandomSlope) == 2)
}

## Chainset
stopifnot("`Chainset` must be a numeric value" = inherits(Chainset, "numeric"))

## Family
stopifnot("`Family` must be a string" = inherits(Family, "character"))

### Poisson cases
if(Family == "poisson"){
  stopifnot("Family 'poisson' requires an integer response variable." =inherits(Data[[Response]], "integer"))
}


### Binomial cases
if(Family == "binomial"){

  Successes = Data[[Response]]
  stopifnot("Family 'binomial' requires an integer response variable." =inherits(Successes, "integer"))

  if(is.null(Trials)){
    stop("Binomial models require the total number of trials (use `Trial =` for inputing the corresponding variable) and a response variable with the number of successes (use  `Response =` for inputing the variable with the count of successes).")
  }

  Attempts = Data[[Response]]  
  stopifnot("Family 'binomial' requires an integer trial variable." =inherits(Attempts, "integer"))

}


## Seed
if(is.null(Seed)){
 Seed = as.numeric(sample(1000:9999, 1))
} else {
stopifnot("`Seed` must be numeric" = inherits(Seed, "numeric"))
}

## PriorSamples
stopifnot("`PriorSamples` must be logical" = inherits(PriorSamples, "logical"))


# Test function 
testfunction = function(){
  emojis = c("\U1F600", "\U1F604", "\U1F601", "\U1F643", "\U1F609", "\U1F60A", "\U1F929", 
  "\U1F917", "\U1F92D", "\U1F973", "\U1F920", "\U1F978", "\U1F60E", "\U1F913", "\U1F47D", 
  "\U1F638", "\U1F596", "\U1F44C", "\U270C", "\U1F44D", "\U1F44F", "\U1F64C", "\U1F40C", 
  "\U1F41B", "\U1F41E", "\U1F997")  
  
  print(paste("No problems so far", sample(emojis, size = 1)))
}

testfunction()


  
# Setting chains 
if(Chainset ==0){
  Warmup=10; Iter=110; Thin=10; Chains=2
} 

if(Chainset != 0){
  Warmup=15000*Chainset
  Iter=30000*Chainset
  Thin=15*Chainset
  Chains=2
}


# Add an observation ID for models of binomial or poisson families
if(Family == "binomial" | Family == "poisson"){
  Data = Data %>%
  dplyr::mutate(observationID = as.factor(dplyr::row_number(Data)))
}

# Construct model formula if binomial family 
if(Family == "binomial"){
    
    if(is.null(RandomEffect)) {
      
      if(is.null(RandomSlope)){
        bfform = 
        paste0(Response, " | trials(", Trials, ") ~ ", 
        paste(FixedEffect, collapse = " + "), " + (1|observationID)")
      }
      
      if(!is.null(RandomSlope)) {
        bfform = 
        paste0(Response, " | trials(", Trials, ") ~ ", paste(FixedEffect, collapse = " + "), 
        " + (1 + ", RandomSlope[1], " |", RandomSlope[2], ") + (1|observationID)")
      }
    }
  
    if(!is.null(RandomEffect)) {
        
      if(is.null(RandomSlope)){
        bfform = 
        paste0(Response, " | trials(", Trials, ") ~ ", paste(FixedEffect, collapse = " + "),
        " + ", paste("(1|", RandomEffect, ")", sep = "", collapse = " + "), " + (1|observationID)")
      }
        
      if(!is.null(RandomSlope)){ 
          bfform = 
          paste0(Response, " | trials(", Trials, ") ~ ", paste(FixedEffect, collapse = " + "),
          " + (1 + ", RandomSlope[1], " |", RandomSlope[2],") + ", 
          paste("(1|", RandomEffect, ")", sep = "", collapse = " + ")," + (1|observationID)")
      }
      }
    }
  

# Construct the formula object if poisson family
  
if(Family == "poisson"){
    
    if(is.null(RandomEffect)) {
      
      if(is.null(RandomSlope)){
        bfform = 
          paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "), " + (1|observationID)")
      } 
        
      if(!is.null(RandomSlope)){
        bfform = 
          paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "),
        " + (1 + ", RandomSlope[1], " |", RandomSlope[2], ") + (1|observationID)")
      }
    }
    
    
    
    if(!is.null(RandomEffect)) {  
      
      if(is.null(RandomSlope)){
        bfform = 
        paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "), " + ",
        paste("(1|", RandomEffect, ")", sep = "", collapse = " + "), " + (1|observationID)")
      }
      
      if(!is.null(RandomSlope)){    
        bfform = 
        paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "), 
        " + (1 + ", RandomSlope[1], " |", RandomSlope[2],") + ", 
        paste("(1|", RandomEffect, ")", sep = "", collapse = " + "), " + (1|observationID)")
        }
      }
    }

# Construct the formula object for gaussian families
if(Family == "gaussian"){
    
    if(is.null(RandomEffect)) {
      
      if(is.null(RandomSlope)){
        bfform = 
        paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "))
      } 
      
      if(!is.null(RandomSlope)){
        bfform = 
        paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "),
        " + (1 + ", RandomSlope[1], " |", RandomSlope[2], ")")
      }
    }
  
    if(!is.null(RandomEffect)) {
      
      if(is.null(RandomSlope)){
        bfform = 
        paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "), " + ", 
        paste("(1|", RandomEffect, ")", sep = "", collapse = " + "))
      } 
      
      if(!is.null(RandomSlope)){
        bfform = 
        paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "),
        " + (1 + ", RandomSlope[1], " |", RandomSlope[2],") + ",
        paste("(1|", RandomEffect, ")", sep = "", collapse = " + "))
      }
    }
  }


mod =  brms::brm(brms::bf(stats::as.formula(bfform)),
                family = Family,
                data = Data, 
                warmup = Warmup,
                iter = Iter, 
                thin=Thin, 
                chains = Chains, 
                init = "random", 
                seed = Seed, 
                cores = parallel::detectCores(), 
                control = list(adapt_delta = 0.999), 
                sample_prior = PriorSamples)

brmsfit = mod

if(max(tidybayes::summarise_draws(mod)$rhat) > 1.1){
  warning("Model did not converge. Try increasing the value of `Chainset`.")
}

return(brmsfit)

}


