# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


#' Run a brms model
#'
#' @param Data A data frame containing the data - covariates should be centered to a the mean or to a meaningful zero (see Schielzeth H. 2010. Simple means to improve the interpretability of regression coefficients. Methods Ecol Evol. 1:103–113. doi:10.1111/j.2041-210X.2010.00012.x.).
#' @param Response String with the name of the column in Data containing the response variable (e.g. "mass"). 
#' @param FixedEffect String with the name of the column in Data containing the fixed effect variable (e.g. "height"). To add multiple fixed effects, use c() (e.g. c("height", "sex")). 
#' @param RandomEffect String with the name of the column in Data containing the random effect variable (e.g. "species"). The current package version allows the use of a single random effect.
#' @param RandomSlope String with the name of the column in Data containing the covariate to be added as a random slope (e.g. "height"). The current package version allows the use of a single random slope.
#' @param Chainset Defines the number of iterations. Start with Chainset = 1 and increase as needed until convergence. The value of chainset is multiplied by 15000 in warmup, 30000 in iterations and 15 in thin intervale. For quick tests use Chainset = 0 (warmup=10; iter=110; thin=10; chains=2) 
#' @param Family String to define the family function in the brms model. Current supported families: "gaussian", "binomial", "poisson".
#' @param Seed Numeric and optional. Set a seed in order to repeat the results from the model when running it more than once. 
#' @param Trials The total number of trials in a binomial model. The number of successes should be imputed on Response.
#' @param PriorSamples Logical value that defines if brmsfit will contain the priors used. Default is set to `FALSE`, which does not includ the priors in the brmsfit. 
#'
#' @return Returns a brmsfit
#' @import BH
#' @export 
#'
#' @examples
#'
#' md = dplyr::starwars
#'
#' # Centering variables
#' md = md %>% 
#'   dplyr::select(mass, sex, height, species) %>% 
#'   dplyr::mutate(mass = log(mass),
#'          sex = dplyr::recode(sex, "male" = 1, 
#'                       "female" = -1, 
#'                       "hermaphroditic" = 0,
#'                       "none" = as.numeric(NA)))
#'   
#'   
#' mod = brms_model(Chainset = 0, 
#'            Response = "mass", 
#'            FixedEffect = c("sex","height"), 
#'            RandomEffect = "species", 
#'            RandomSlope = "height",
#'            Family = "gaussian", 
#'            Data = md, 
#'            Seed = 0405)
#'
#' print(mod)
#'
#' plot(mod)
#'

brms_model = function(Data, Response, FixedEffect, RandomEffect = NULL, RandomSlope = NULL, Chainset = 1, Family = "gaussian", Seed = NULL, Trials = NA, PriorSamples = TRUE){
stopifnot("`Data` must be a data frame" =               
              inherits(Data, "data.frame"))
  
stopifnot("`Response` must be a string" =               
              inherits(Response, "character"))

if(Family == "binomial"){
  Successes = Data[[Response]]
  stopifnot("Family 'binomial' requires an integer response variable." =inherits(Successes, "integer"))
}

if(Family == "binomial"){
  Attempts = Data[[Trials]]
  stopifnot("Family 'binomial' requires an integer trial variable." =inherits(Attempts, "integer"))
  }

  
if(Family == "poisson"){
  Resp = Data[[Response]]
  stopifnot("Family 'poisson' requires an integer response variable." =inherits(Resp, "integer"))
}


stopifnot("`FixedEffect` must be a string" =               
              inherits(FixedEffect, "character"))

if(!is.null(RandomEffect)) {stopifnot("`RandomEffect` must be a string" =               
              inherits(RandomEffect, "character"))}

if(!is.null(RandomSlope)){stopifnot("`RandomSlope` must be a string" =               
              inherits(RandomSlope, "character"))}

stopifnot("`Chainset` must be a numeric value" =               
              inherits(Chainset, "numeric"))

stopifnot("`Family` must be a string" =               
              inherits(Family, "character"))

if(Family == "binomial" && is.na(Trials)){
stop("Binomial models require the total number of trials (use `Trial =` for inputing the corresponding variable) and a response variable with the number of successes (use `Response =` for inputing the variable with the count of successes).")}

if(is.null(Seed)){
 Seed = sample(1000:9999, 1)
} else {
stopifnot("`Seed` must be numeric" =               
              inherits(Seed, "numeric"))
  } 

stopifnot("`PriorSamples` must be logical" =               
              inherits(PriorSamples, "logical"))


testfunction = function(){

emojis = c("\U1F600", "\U1F604", "\U1F601", "\U1F643", "\U1F609", "\U1F60A", "\U1F929", "\U1F917", "\U1F92D", "\U1F973", "\U1F920", "\U1F978", "\U1F60E", "\U1F913", "\U1F47D", "\U1F638", "\U1F596", "\U1F44C", "\U270C", "\U1F44D", "\U1F44F", "\U1F64C", "\U1F40C", "\U1F41B", "\U1F41E", "\U1F997")  

print(paste("No problem", sample(emojis, size = 1)))
}

testfunction()
  
# Setting chains 
if(Chainset==0){Warmup=10; Iter=110; Thin=10; Chains=2
} else {
Warmup=15000*Chainset
Iter=30000*Chainset
Thin=15*Chainset
Chains=2}

# Add an observation ID for models of binomial or poisson families
if(Family == "binomial" | Family == "poisson"){

Data = Data %>%
  dplyr::mutate(observationID = as.factor(dplyr::row_number(Data)))

}


# Construct model formula if binomial family 
if(Family == "binomial"){

  bfform = 
    
    if(is.null(RandomEffect)) {
      paste0(Response, " | trials( ", Trials, ") ~ ", paste(FixedEffect, collapse = " + "), " + (1|observationID)")
      } else {
        if(is.null(RandomSlope)){
        paste0(Response, " | trials( ", Trials, ") ~ ", 
               paste(FixedEffect, collapse = " + "),
        "+ ( 1 | ", RandomEffect," ) + (1|observationID)")
          } else {
          paste0(Response, " | trials( ", Trials, ") ~ ",
                 paste(FixedEffect, collapse = " + "),
                 "+ ( 1 +", RandomSlope, " | ", 
                 RandomEffect," ) + (1|observationID)")}}

} else {

# Construct the formula object if poisson family
  
if(Family == "poisson"){

bfform = 
    
    if(is.null(RandomEffect)) {
      paste0(Response, " ~ ", paste(FixedEffect, collapse = " + "), " + (1|observationID)")
      } else {
        if(is.null(RandomSlope)){
        paste0(Response, " ~ ", 
               paste(FixedEffect, collapse = " + "),
        "+ ( 1 | ", RandomEffect," ) + (1|observationID)")
          } else {
          paste0(Response, " ~ ",
                 paste(FixedEffect, collapse = " + "),
                 "+ ( 1 +", RandomSlope, " | ", 
                 RandomEffect," ) + (1|observationID)")}}
} else {
  
# Construct the formula object for other model families
  

  bfform = 
    
    if(is.null(RandomEffect)) {
      paste0(Response, "~", paste(FixedEffect, collapse = " + "))
      } else {
        if(is.null(RandomSlope)){
        paste0(Response, "~", paste(FixedEffect, collapse = " + "),
        "+ ( 1 | ", RandomEffect," )")
          } else {
          paste0(Response, "~",
                 paste(FixedEffect, collapse = " + "),
                 "+ ( 1 +", RandomSlope, " | ", RandomEffect," )")}}
        
}
}

  mod =  brms::brm(brms::bf(stats::as.formula(bfform)),
                  family = Family,
                  data = Data, 
                  warmup = Warmup,
                  iter = Iter, 
                  thin=Thin, 
                  chains = Chains, 
                  init = "random", 
                  seed = Seed, 
                  cores = parallel::detectCores(), 
                  control = list(adapt_delta = 0.999), 
                  sample_prior = PriorSamples)

brmsfit = mod

if(max(tidybayes::summarise_draws(mod)$rhat) > 1.1){
warning("Model did not converge. Try increasing the value of `Chainset`.")}

return(brmsfit)

}

