# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand


#' Compare slope values of different brms models
#'
#' @param brmsfit A list of brms models to be compared
#' 
#' @param Slope A string containing the name of the covariate to have the slopes compared between models
#'
#' @return Returns a table of values with the log(slope model 1/slope model 2) 
#' @export 
#'
#' @examples
#'
#' md = dplyr::starwars
#'
#' # Centering variables
#' md = md %>% 
#'   dplyr::select(mass, sex, height, species) %>% 
#'   dplyr::mutate(mass = log(mass),
#'          sex = dplyr::recode(sex, "male" = 1, 
#'                       "female" = -1, 
#'                       "hermaphroditic" = 0,
#'                       "none" = as.numeric(NA)))
#'   
#'   
#' mod1 = brms_model(Chainset = 0,
#'                   Response = "mass", 
#'            FixedEffect = "sex", 
#'            Family = "gaussian", 
#'            Data = md)
#'
#' mod2 = brms_model(Chainset = 0,
#'                   Response = "mass", 
#'            FixedEffect = "sex",
#'            RandomEffect = "species",
#'            RandomSlope = "sex",
#'            Family = "gaussian", 
#'            Data = md)
#'
#' compare_slopes(mod1, mod2, Slope = "sex")

compare_slopes = function(..., Slope){

  # Capture all the arguments into a list
  brmsfit_list = list(...)

  # Check if all elements are of class 'brmsfit'
  stopifnot("All inputs must be brmsfit objects" = 
              (sapply(brmsfit_list, inherits, "brmsfit"))) 
  
  stopifnot("This function allows comparing only two models at a time" = 
              length(brmsfit_list) == 2) 
  
  stopifnot("Slope must be a string" = 
             inherits(Slope, "character"))
  
  
mean_slope_mod1 = mean(as.data.frame(brmsfit_list[[1]])[[paste0("b_", Slope)]],na.rm=TRUE)
mean_slope_mod2 = mean(as.data.frame(brmsfit_list[[2]])[[paste0("b_", Slope)]],na.rm=TRUE)
  

  lnR = log(mean_slope_mod1/mean_slope_mod2)


return(lnR)  

}

