# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' mod
#' model with fixed effects only
#' @format brmsfit
#' @import BH
#' @import brms
#' @import rstan
#' @import RcppEigen

md = dplyr::starwars

# Centering variables
md = md %>% 
  dplyr::select(mass, sex, height, species) %>% 
  dplyr::mutate(mass = log(mass),
         sex = dplyr::recode(sex, "male" = 1, 
                      "female" = -1, 
                      "hermaphroditic" = 0,
                      "none" = as.numeric(NA)))


mod = brms_model(Chainset = 2,
                 Response = "mass", 
                 FixedEffect = c("sex","height"), 
                 Family = "gaussian", 
                 Data = md)
