# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' model with fixed effects and a random effect with a covariance matrix
#' @format A `brmsfit` object.
#' @source Generated using the `brms_cov_model` function.

"mod_cov"

