# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Example model with fixed and random effects
#' @format A `brmsfit` object.
#' @source Generated using the `brms_model` function.

"mod_RE"

