# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' mod_RE
#' model with fixed effects and random effects
#' @format brmsfit
#' @import BH
#' @import brms
#' @import rstan
#' @import RcppEigen

md = dplyr::starwars

# Centering variables
md = md %>% 
  dplyr::select(mass, sex, height, species) %>% 
  dplyr::mutate(mass = log(mass),
         sex = dplyr::recode(sex, "male" = 1, 
                      "female" = -1, 
                      "hermaphroditic" = 0,
                      "none" = as.numeric(NA)))


# With random effect
mod_RE = brms_model(Chainset = 2,
                     Response = "mass", 
                     FixedEffect = c("sex","height"), 
                     RandomEffect = "species", 
                     Family = "gaussian", 
                     Data = md)
