# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Variance decomposition for brms models
#'
#' @param brmsfit The output of a brms model. You can use VarDecomp::brms_model() to produce a brmsfit. 
#'
#' @return Returns a data frame with the summaries of posterior estimates.
#'
#' @export
#'
#' @examples
#' \dontrun{
#'
#' md = dplyr::starwars
#'
#' # Centering variables
#' md = md %>% 
#'   dplyr::select(mass, sex, species) %>% 
#'   dplyr::mutate(mass = log(mass),
#'          sex = dplyr::recode(sex, "male" = 1, 
#'                       "female" = -1, 
#'                       "hermaphroditic" = 0,
#'                       "none" = as.numeric(NA)))
#'   
#'   
#' mod = brms_model(Chainset = 2,
#'                  Response = "mass", 
#'                  FixedEffect = "sex", 
#'                  RandomEffect = "species",
#'                  Family = "gaussian", 
#'                  Data = md)
#'
#' model_summary(mod)
#'
#' }
model_summary = function(brmsfit){

  stopifnot("Input must be a brmsfit" =               
              inherits(brmsfit, "brmsfit"))
  

output = VarDecomp::var_decomp(brmsfit)

EstSummary = posterior::summarise_draws(output) %>% 
  dplyr::select(variable, mean, median, sd) 
  
#Highest probability density interval
HPDInt = as.data.frame(coda::HPDinterval(mcmcr::as.mcmc(output, combine_chains = TRUE))) %>% 
  tibble::rownames_to_column(var = "variable")

  EstSummary = dplyr::left_join(EstSummary, HPDInt, by = "variable") %>% 
  dplyr::mutate(dplyr::across(where(is.numeric), \(x) round(x, 3))) %>% 
  dplyr::rename(lower_HPD = lower, upper_HPD = upper) %>% 
        dplyr::filter(!grepl("sigma", variable))
  
return(EstSummary)   

}

