# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Model summaries with variance decomposition for brms models 
#' 
#' @param brmsfit The output of a brms model. You can use VarDecomp::brms_model() to produce a brmsfit. 
#'
#' @return Returns a data frame with the summaries of posterior estimates.
#' @import posterior
#' @export
#'
#' @examples
#'
#' # Simulate data
#' md = tibble::tibble(
#'   group = factor(sample(1:10, 1000, replace = TRUE)),
#'   f_var = factor(sample(1:3, 1000, replace = TRUE)),
#'   n_var = rnorm(1000, mean = 0, sd = 1),
#'   resp = rnorm(1000, mean = 10, sd = 3))
#'
#' # Run model
#' mod = brms_model(Response = "resp", 
#'                  FixedEffect = c("f_var","n_var"), 
#'                  RandomEffect = "group", 
#'                  Family = "gaussian", 
#'                  Data = md)
#'
#' # Model summary
#'
#' model_summary(mod)
#'
model_summary = function(brmsfit){

  stopifnot("Input must be a brmsfit" =               
              inherits(brmsfit, "brmsfit"))
  

output = var_decomp(brmsfit)

EstSummary = posterior::summarise_draws(output) %>% 
  dplyr::select(variable, mean, median, sd) 
  
#Highest probability density interval
HPDInt = as.data.frame(coda::HPDinterval(mcmcr::as.mcmc(output, combine_chains = TRUE))) %>% 
  tibble::rownames_to_column(var = "variable")

EstSummary = dplyr::left_join(EstSummary, HPDInt, by = "variable") %>%  
  dplyr::rename(lower_HPD = lower, upper_HPD = upper) %>% 
        dplyr::filter(!grepl("sigma", variable))

for(i in colnames(EstSummary)){

if(is.numeric(EstSummary[[i]])){
  
  EstSummary = EstSummary %>% 
  dplyr::mutate(!!paste0(i) := round(get(i), 4))
  
  }

}
  
return(EstSummary)   

}

