# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Model example that can be used to test other functions of `VarDecomp`. A model with fixed effects only
 
#' @format A `brmsfit` object.
#' @source Generated using the `brms_model` function.

"mod" 

