# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Several model examples that can be used to test other functions of `VarDecomp` 
#' @format Several `brmsfit` objects.
#' @source Generated using the `brms_model` and `brms_cov_model` functions.

# A model with fixed effects only
"mod" 

# A model with fixed and random effects
"mod_RE"

# A model with random slopes
"mod_RS"

# A model with a covariance matrix
"mod_cov"

