# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Perform model fit checks for brms models
#'
#' @param brmsfit The output of a brms model. You can use VarDecomp::brms_model() to produce a brmsfit. 
#' @param Group A string containing the name of a grouping variable for the visualization of a posterior predictive check plot (e.g. "sex"). 
#' @param Prior A logical argument defining whether the `brmsfit` contains prior samples. If set to `TRUE` it will produce plots comparing the log distributions of priors and posterior samples for each covariate. 
#'
#' @return Returns a list containing (a) the maximum R-hat value, (b) the minimum effective sample size, (c) traceplots, (d) posterior predictive check plots, and (e) prior and posterior sample plots (if priors are available).
#' @export 
#' 
model_fit = function(brmsfit, Group = NULL, Prior = FALSE){


# R-hat and effective sample size

convergence = tibble::tribble(~Rhat, ~EffectiveSampleSize,
               max(posterior::summarise_draws(brmsfit)$rhat), 
               min(posterior::summarise_draws(brmsfit)$ess_bulk))

# Trace plots
traceplot = bayesplot::mcmc_trace(posterior::as_draws_df(brmsfit), 
           pars = dplyr::vars(tidyselect::starts_with("b"), 
                       tidyselect::starts_with("sd"), 
                       -tidyselect::contains("prior")),
           np = bayesplot::nuts_params(brmsfit),
           facet_args = list(ncol = 2), 
           size = 0.15) +


# Posterior predictive checks
ppDens = rstanarm::pp_check(brmsfit, type = "dens_overlay", ndraws = 30) 

ppLoo = rstanarm::pp_check(brmsfit, type = "loo_pit_qq") 

if(!is.null(Group)){
ppGroup = rstanarm::pp_check(brmsfit, type = "violin_grouped",group= Group)}


# Prior samples
if(Prior == TRUE){
priordraws = brms::prior_draws(brmsfit) %>% 
  dplyr::select(tidyselect::starts_with("sd_")) %>%  
  dplyr::pivot_longer(cols = 1, names_to = "variable", values_to = "value")%>%
  tibble::add_column(name = "prior")

posteriordraws = posterior::as_draws_df(brmsfit) %>% 
    dplyr::select(tidyselect::starts_with("sd")) %>% 
    dplyr::rename_with(stringr::str_remove(~stringr::str_remove_all(., "__Intercept"))) %>% 
  tidyr::gather(key = "variable", value = "value") %>%
  tibble::add_column(name = "posterior")

priorposterior= dplyr::bind_rows(priordraws,posteriordraws) %>% 
  dplyr::mutate(value=log(value))

priorsample = 
  ggplot2::ggplot(data=priorposterior, aes(x=value, fill = name, color = name))+
  ggplot2::geom_density(alpha=0.6, size=0.8)+
  ggplot2::scale_fill_manual(values=c("#B3CDE0","#8ECAE6"))+
  ggplot2::scale_color_manual(values=c("#B3CDE0","#8ECAE6"))+
  ggplot2::theme_classic()
}


if(is.null(Group)){
  if(is.null(Prior)){
  return(list(convergence,
            traceplot,
            ppDens, 
            ppLoo))
  }else{
        return(list(convergence,
            traceplot,
            ppDens, 
            ppLoo, 
            priorsample))
    }
}else{
  if(is.null(Prior)){
    return(list(convergence,
            traceplot,
            ppDens, 
            ppLoo, 
            ppGroup))
  }else{
      return(list(convergence,
            traceplot,
            ppDens, 
            ppLoo, 
            ppGroup, 
            priorsample))
  }
  }

  
}
