# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Perform model fit checks for brms models
#'
#' @param brmsfit The output of a brms model. You can use VarDecomp::brms_model() to produce a brmsfit. 
#' @param Group A string containing the name of a grouping variable for the visualization of a posterior predictive check plot (e.g. "sex"). To add multiple grouping variables, use c() (e.g. c("sex", "species")). 
#' @param Prior A logical argument defining whether the `brmsfit` contains prior samples. If set to `TRUE` it will produce plots comparing the log distributions of priors and posterior samples for each covariate. 
#'
#' @return Returns a list containing (a) the maximum R-hat value, (b) the minimum effective sample size, (c) traceplots, (d) posterior predictive check plots, and (e) prior and posterior sample plots (if priors are available).
#' @export 
#' 
#' @examples
#' md = dplyr::starwars
#'
#' # Centering variables
#' md = md %>% 
#'   dplyr::select(mass, sex, height, species) %>% 
#'   dplyr::mutate(mass = log(mass),
#'          sex = dplyr::recode(sex, "male" = 1, 
#'                       "female" = -1, 
#'                       "hermaphroditic" = 0,
#'                       "none" = as.numeric(NA)))
#'
#'
#' # Without random effects
#'
#' mod = brms_model(Chainset = 2,
#'                  Response = "mass", 
#'                  FixedEffect = c("sex","height"), 
#'                  Family = "gaussian", 
#'                  Data = md,
#'                  PriorSamples = TRUE)
#'
#' model_fit(mod, Group = "sex", Prior = TRUE)
model_fit = function(brmsfit, Group = NULL, Prior = FALSE){


# R-hat and effective sample size

convergence = tibble::tribble(~Rhat, ~EffectiveSampleSize,
               max(posterior::summarise_draws(brmsfit)$rhat), 
               min(posterior::summarise_draws(brmsfit)$ess_bulk))

# Trace plots
traceplot = bayesplot::mcmc_trace(posterior::as_draws_df(brmsfit), 
           pars = dplyr::vars(tidyselect::starts_with("b"), 
                       tidyselect::starts_with("sd"), 
                       -tidyselect::contains("prior")),
           np = bayesplot::nuts_params(brmsfit),
           facet_args = list(ncol = 2), 
           size = 0.15) 

nd = nrow(as.data.frame(brmsfit))

# Posterior predictive checks
ppDens = rstanarm::pp_check(brmsfit, type = "dens_overlay", ndraws = (nd*0.2)) 

ppLoo = rstanarm::pp_check(brmsfit, type = "loo_pit_qq") 

if(!is.null(Group)){

for (i in Group){
plot = rstanarm::pp_check(brmsfit, type = "violin_grouped",group= i) +
  ggtitle(i)
assign(paste0("GroupPlot_", i), plot) 
}

ppGroup = list()   

GroupNames = ls(pattern = "^GroupPlot")
for (i in GroupNames) {
    ppGroup[[i]] = get(i)
}
}

# Prior samples
if(Prior == TRUE){
priordraws = brms::prior_draws(brmsfit) %>% 
  dplyr::select(tidyselect::starts_with("sd_"))  
  
if(length(priordraws)==0){
  priorsample = "No prior samples to plot"
}else{
 priordraws = priordraws %>% 
 tidyr::pivot_longer(cols = 1, names_to = "variable", values_to = "value")%>%
  tibble::add_column(name = "prior")

posteriordraws = as.data.frame(brmsfit) %>% 
    dplyr::select(tidyselect::starts_with("sd")) %>%
    dplyr::select(tidyselect::contains("Intercept")) %>%
    dplyr::rename_with(~ stringr::str_remove_all(., "__Intercept")) %>% 
  tidyr::gather(key = "variable", value = "value") %>%
  tibble::add_column(name = "posterior")

priorposterior= dplyr::bind_rows(priordraws,posteriordraws) %>% 
  dplyr::mutate(value=log(value)) %>% 
  dplyr::rename_with(~ stringr::str_remove_all(., "sd_"))



priorsample = 
  ggplot2::ggplot(priorposterior, ggplot2::aes(value, fill = name, color = name)) +
  ggplot2::geom_density(alpha=0.6, linewidth=0.8) +
  ggplot2::scale_fill_manual(values=c("#B3CDE0","#8ECAE6")) +
  ggplot2::scale_color_manual(values=c("#B3CDE0","#8ECAE6")) +
  ggplot2::theme_test()+
  ggplot2::facet_wrap(~variable)
 
}

}


if(is.null(Group)){
  if(isFALSE(Prior)){
  output = list(convergence,
            traceplot,
            ppDens, 
            ppLoo)
  names(output) = c("R-hat and Effective sample size", "Traceplots plot", "Posterior predictive check - Density overlay plot", "Posterior predictive check - LOO-PIT-QQ plot")
  }else{
    output = list(convergence,
            traceplot,
            ppDens, 
            ppLoo, 
            priorsample)
      names(output) = c("R-hat and Effective sample size", "Traceplots plot", "Posterior predictive check - Density overlay plot", "Posterior predictive check - LOO-PIT-QQ plot","Prior samples plot") 
    }
}else{
  if(isFALSE(Prior)){

    output = list(convergence,
            traceplot,
            ppDens, 
            ppLoo, 
            ppGroup)
      names(output) = c("R-hat and Effective sample size", "Traceplots plot", "Posterior predictive check - Density overlay plot", "Posterior predictive check - LOO-PIT-QQ plot", "Posterior predictive check - Group density overlay plot")
  }else{
      output = list(convergence,
            traceplot,
            ppDens, 
            ppLoo, 
            ppGroup, 
            priorsample)
      
       names(output) = c("R-hat and Effective sample size", "Traceplots plot", "Posterior predictive check - Density overlay plot", "Posterior predictive check - LOO-PIT-QQ plot", "Posterior predictive check - Group density overlay plot", "Prior samples plot")
  }
}

return(output)
  
}
