# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Model example that can be used to test other functions of `VarDecomp`. A model with random slopes.
#' @format A `brmsfit` object.
#' @source Generated using the `brms_model` function.

"mod_RS"


#' Model example that can be used to test other functions of `VarDecomp`. A model with a covariance matrix.
#' @format A `brmsfit` object.
#' @source Generated using the `brms_model` function.

"mod_cov"


#' Model example that can be used to test other functions of `VarDecomp`. A model with fixed effects only
 
#' @format A `brmsfit` object.
#' @source Generated using the `brms_model` function.

"mod" 


#' Model example that can be used to test other functions of `VarDecomp`. A model with fixed and random effects
#' @format A `brmsfit` object.
#' @source Generated using the `brms_model` function.

"mod_RE"

