# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Plot R2 values of brms models
#'
#' @param PosteriorSamples The estimates of a brms model after variance decomposition. You can use VarDecomp::brms_model() to produce a brmsfit and then VarDecomp::var_decomp() to produce the posterior samples. 
#' @param Colors A vector with string of the colors to be attributed to each variable ordered by R2, with residual at the end (e.g. c("blue", "green", "gray")).
#' @return Returns a bar plot with the proportion of variance explained by each variable.
#' @export 
#' 
#' @examples
#' \dontrun{
#' md = dplyr::starwars
#'
#' # Centering variables
#' md = md %>% 
#'   dplyr::select(mass, sex, species) %>% 
#'   dplyr::mutate(mass = log(mass),
#'          sex = dplyr::recode(sex, "male" = 1, 
#'                       "female" = -1, 
#'                       "hermaphroditic" = 0,
#'                       "none" = as.numeric(NA)))
#'   
#'   
#' mod = brms_model(Chainset = 2,
#'                  Response = "mass", 
#'                  FixedEffect = "sex", 
#'                  RandomEffect = "species",
#'                  Family = "gaussian", 
#'                  Data = md)
#'
#' PosteriorSamples = var_decomp(mod)
#' plot_R2(PosteriorSamples)
#'
#' }
#'

plot_R2 = function(PosteriorSamples, Colors = NULL){

stopifnot("Input must be a data frame containing estimates after variance decomposition. You can use VarDecomp::var_decomp() to produce the input data." = inherits(PosteriorSamples, "data.frame"))

stopifnot("Input must be a data frame containing estimates after variance decomposition. You can use VarDecomp::var_decomp() to produce the input data." = any(stringr::str_detect(names(PosteriorSamples), "R2")) == TRUE) 

if(!is.null(Colors)){
stopifnot("Colors input must be a vector containing strings with the colors to be attributed to each category in the stacked bar plot (e.g. c(`blue`, `green`, `gray`))." = inherits(Colors, "character"))
}  
  
PS = PosteriorSamples %>% 
  dplyr::select(dplyr::starts_with("R2_")) %>% 
  dplyr::rename_with(~ stringr::str_remove(., "^R2_")) %>% 
  dplyr::select(!sum_fixed_effects) %>% 
  dplyr::summarise(dplyr::across(tidyselect::everything(), mean, na.rm = TRUE))

for (i in colnames(PS)) {
  RS = unlist(strsplit(i, "_"))
  
  # Check if both parts exist as separate columns
  if (length(RS) == 2 && all(RS %in% colnames(PS))) {
    # Remove the concatenated column
    PS = PS %>% 
    dplyr::select(-all_of(i))
  }
  }  

PS = PS %>%
  tidyr::pivot_longer(cols = everything(), 
  names_to = "Variable",
  values_to = "R2")

PS = PS %>%
  dplyr::arrange(R2) %>% 
  dplyr::mutate(ID = "")

PS = PS %>%
  dplyr::mutate(Variable = factor(Variable, 
  levels = c(setdiff(PS$Variable, "residual"), "residual")))

 if(is.null(Colors)){
  variable_colors = setNames(rep("lightgrey", length(levels(PS$Variable))), levels(PS$Variable))
  variable_colors[names(variable_colors) != "residual"] = scales::hue_pal()(length(levels(PS$Variable)) - 1)
 }  else {
  variable_colors = Colors
}

ggplot2::ggplot(PS, ggplot2::aes(x = ID, y = R2, fill=Variable)) +
ggplot2::geom_bar(stat="identity") +

ggplot2::geom_text(ggplot2::aes(label = round(R2*100, 2)), 
              position = ggplot2::position_fill(vjust = 0.5), 
              color = "white", size = 3) +
ggplot2::scale_fill_manual(values = variable_colors) +
ggplot2::labs(x = NULL, y = "Proportion of total variance explained")+
ggplot2::theme_test()
}

