# WARNING - Generated by {fusen} from dev/VarDecomp_package.Rmd: do not edit by hand

#' Variance decomposition for brms models
#'
#' @param brmsfit The output of a brms model. You can use VarDecomp::brms_model() to produce a brmsfit. 
#'
#' @return Returns a data frame with the summaries of posterior estimates.
#'
#' @export
#'
#' @examples
#'
#' #var_decomp(mod_RS)
#'
var_decomp = function(brmsfit){

# Extract original data
  Data = brmsfit$data
  
  Data = Data %>% 
    tidyverse::filter(tidyverse::if_all(1:ncol(Data),~ !is.na(.)))
  
  
# Extract posterior samples
  PS = as.data.frame(brmsfit) %>% 
  tidyverse::select(!tidyverse::starts_with("r")) %>% 
  tidyverse::select(!tidyverse::contains("prior")) %>% 
  tidyverse::select(!lp__)
 

if("Intercept" %in% colnames(PS)){PS = PS %>% tidyverse::select(-Intercept)}

#Extract family
Family = brmsfit$family[[1]][1]

#Extract fixed effect names
PS_b = PS %>% 
  tidyverse::select(tidyverse::starts_with("b_")) %>% 
  tidyverse::rename_with(~ tidyverse::str_remove(., "^b_")) %>%  
  tidyverse::select(!Intercept)

FixedEffect = colnames(PS_b)

#Extract random effect names
PS_sd = PS %>% 
  tidyverse::select(tidyverse::starts_with("sd_")) %>% 
  tidyverse::rename_with(~ tidyverse::str_remove(., "^sd_"))

if(Family == "binomial" | Family == "poisson"){

  PS_RE = PS_sd %>% 
  tidyverse::select(tidyverse::ends_with("Intercept")) %>% 
  tidyverse::select(!tidyverse::contains("observationID")) %>% 
  tidyverse::rename_with(~ tidyverse::str_remove(., "__Intercept"))

} else {

PS_RE = PS_sd %>% 
  tidyverse::select(tidyverse::ends_with("Intercept")) %>% 
  tidyverse::rename_with(~ tidyverse::str_remove(., "__Intercept"))
}

if(ncol(PS_RE) == 0){RandomEffect = NULL
} else {
  RandomEffect = colnames(PS_RE)
}


#Extract random slope names

PS_RS = PS_sd %>% 
  tidyverse::rename_with(~ tidyverse::str_replace_all(., "__", "_")) %>% 
  tidyverse::select(!tidyverse::ends_with("Intercept"))

if(ncol(PS_RS) == 0){RandomSlope = NULL
} else {
  RandomSlope = colnames(PS_RS)
RandomSlope = gsub(paste0(RandomEffect, "_"), "", RandomSlope)
}
  



#Rename columns for tidying the data
PS = PS %>% 
  tidyverse::rename_with(~tidyverse::str_remove_all(., "^b_")) %>% 
  tidyverse::rename_with(~tidyverse::str_remove_all(., "sd_")) %>% 
  tidyverse::rename_with(~tidyverse::str_replace_all(., "__", "_")) %>% 
  tidyverse::rename_with(~tidyverse::str_remove_all(., "_Intercept")) 


# Variance in fixed effects

## Create a dataframe with the values used by the model for fixed effects
if(!is.null(RandomEffect)){
  FixedEffectData = Data %>% 
  tidyverse::select(c(setdiff(colnames(Data), RandomEffect))) %>% 
  tidyverse::select(-1)  #Removing the response variable
} else {
  FixedEffectData = Data %>% 
  tidyverse::select(-1)  #Removing the response variable
  }
  
## Specific for covariates with of character class 
suppressWarnings({  CharactersFE = FixedEffectData%>%
  tidyverse::select(-tidyverse::one_of(FixedEffect)) })
  
  if(ncol(CharactersFE) == 0){
    
  } else{
  
for(i in colnames(CharactersFE)){
unique_values = unique(CharactersFE[[i]])

for (j in unique_values) {

  CharactersFE = CharactersFE %>% 
    tidyverse::mutate(!!paste(j) := tidyverse::if_else(CharactersFE[[i]] == j, 1,0)) %>% 
    tidyverse::rename(!!paste0(i, j) := paste(j)) 
  
}
CharactersFE = CharactersFE 
}

FixedEffectData = tidyverse::bind_cols(FixedEffectData,CharactersFE) %>% 
  tidyverse::select_if(~ is.numeric(.))
}

## Calculate estimated variances for each fixed effect

for (i in colnames(FixedEffectData)){
  if (i %in% colnames(PS)) {
        PS = PS %>% 
           tidyverse::mutate(!!paste0("var_", i) := get(paste0(i))*
               var(FixedEffectData[[paste0(i)]]))
  
  }
  }

# Total variance in fixed effects
FixedEffectNames = intersect(names(PS), paste0("var_", names(FixedEffectData)))

PS = PS %>% 
tidyverse::mutate(var_FixedEffects = rowSums(tidyverse::across(tidyverse::all_of(FixedEffectNames)), na.rm = TRUE))
  
  
# Calculate the estimated variances in random slope

if(!is.null(RandomSlope)){
  
  
  PS = PS %>% 
  tidyverse::mutate(!!paste0("var_", RandomEffect, "_", RandomSlope) := (get(paste0(RandomEffect, "_", RandomSlope))^2 *
                  var(FixedEffectData[[RandomSlope]])) +
                
                 (get(paste0(RandomEffect,"_", RandomSlope))^2 *
                  mean(FixedEffectData[[RandomSlope]])))
  }


           
# Variances in random effect
if(!is.null(RandomEffect)){
PS = PS %>% 
  tidyverse::mutate(!!paste0("var_", RandomEffect) := 
           
        # for models without random slopes
          ifelse(RandomSlope == FALSE, 
                 get(paste0(RandomEffect))^2,
        
        # for models with random slope (in Holger's paper on random slopes)
                 (get(paste0(RandomEffect))^2) +
                  
              (get(paste0("var_", RandomEffect, "_", RandomSlope))) +
                        
                (get(paste0("cor_", RandomEffect, "_",
                            RandomSlope))) *
                   get(paste0(RandomEffect)) *
                   get(paste0(RandomEffect,"_", RandomSlope)) *
                   2 *  mean(FixedEffectData[[RandomSlope]])))
}
                            
# Residual variance
if(Family == "gaussian"){
PS = PS %>% 
  tidyverse::mutate(residual = sigma^2)

} else {
  if(Family == "binomial"){

    PS = PS %>% 
      tidyverse::mutate(residual = observationID^2 + (pi^2/3))

    } else {
     if(Family== "poisson") {
       
      PS = PS %>% 
        tidyverse::mutate(residual =  observationID^2 + 
                                    log(1/exp(Intercept)+1))
     
     } else {
       
       stop("`The family of this model is not yet supported by var_decomp function")
    
       
  }
  }
  }

# Total phenotypic variance
if(!is.null(RandomEffect)){
PS = PS %>% 
    tidyverse::mutate(total_pv = var_FixedEffects + 
           get(paste0("var_", RandomEffect)) + 
           residual) 

} else {
PS = PS %>% 
    tidyverse::mutate(total_pv = var_FixedEffects + 
           residual)   
}


# calculate R2 for fixed effects

for (i in FixedEffectNames){
        PS = PS %>% 
           tidyverse::mutate(!!paste0("R2_", i) := get(paste0(i))/total_pv)
}

PS = PS %>% 
tidyverse::mutate(R2_FixedEffects = rowSums(tidyverse::across(tidyverse::all_of(paste0("R2_", FixedEffectNames))), na.rm = TRUE))%>%          tidyverse::rename_with(~tidyverse::str_replace_all(., "_var_", "_"), tidyverse::contains("_var_"))

# calculate R2 for random slopes
    if(!is.null(RandomSlope)){
      
      PS = PS %>%
        tidyverse::mutate(!!paste0("R2_", RandomEffect, "_", RandomSlope) := 
                   get(paste0("var_", RandomEffect, "_", RandomSlope))/total_pv)
      } 
  

# calculate R2 for random effect
if(!is.null(RandomEffect)){
PS = PS %>% 
  tidyverse::mutate(!!paste0("R2_",RandomEffect) := 
             get(paste0("var_", RandomEffect))/total_pv) 
}
# Residual
PS = PS %>% 
  tidyverse::mutate(R2_residual = 
             residual/total_pv)


output = PS %>% 
  tidyverse::select(-tidyverse::all_of(RandomEffect)) %>% 
  tidyverse::select(-tidyverse::starts_with("var_")) %>% 
  tidyverse::select(-total_pv) %>% 
  tidyverse::select(-residual)




EstSummary = posterior::summarise_draws(output) %>% 
  tidyverse::select(variable, mean, median, sd) 
  
  
#Highest probability density interval
HPDInt = as.data.frame(coda::HPDinterval(mcmcr::as.mcmc(output, combine_chains = TRUE))) %>% 
  tidyverse::rownames_to_column(var = "variable")

EstSummary = tidyverse::left_join(EstSummary, HPDInt, by = "variable") %>%
  tidyverse::mutate(tidyverse::across(where(is.numeric), round, 3)) %>% 
  tidyverse::rename(lower_HPD = lower, upper_HPD = upper) 



return(print(EstSummary))   

}



